### ISSUE TITLE
Project.getRepo is deprecated.

### ISSUE THREAD

**Issue by NishanthShankar** [jacogr/atom-git-control#71] opened 2015-05-07 17:32 UTC
Use ::getRepositories instead
```
Project.getRepo (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:579:12)
Object.<anonymous> (/Users/NeO/.atom/packages/git-control/lib/git.coffee:15:17)
Object.<anonymous> (/Users/NeO/.atom/packages/git-control/lib/git.coffee:289:4)
Module._compile (module.js:452:26)
```

**Comment by nounoursheureux** [comment] 2015-05-07 17:33
Duplicate of #64 and #70 . This bug has been fixed, just wait for the next release :)

**Comment by MarcelMue** [comment] 2015-05-07 17:38
New release is probably going to come next week, until then this warning will pop up.

**Closed by MarcelMue** 2015-05-07 17:38 UTC
