### ISSUE TITLE
GitRepository.getOriginUrl is deprecated.

### ISSUE THREAD

**Issue by sakirsensoy** [jacogr/atom-git-control#68] opened 2015-05-03 23:12 UTC
Use ::getOriginURL instead.
```
GitRepository.getOriginUrl (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:446:7)
Object.hasOrigin (/Users/sakirsensoy/.atom/packages/git-control/lib/git.coffee:127:16)
GitControlView.fetchMenuClick (/Users/sakirsensoy/.atom/packages/git-control/lib/git-control-view.coffee:161:24)
GitControlView.update (/Users/sakirsensoy/.atom/packages/git-control/lib/git-control-view.coffee:68:9)
```

**Comment by MarcelMue** [comment] 2015-05-04 08:44
This is a duplicate of #63 aswell, I am goign to keep it open for now to stop further duplicates.

**Closed** 2015-05-27 10:34 UTC
Labels: deprecated
