### ISSUE TITLE
Project.getRepo is deprecated.

### ISSUE THREAD

**Issue by Khogniak** [jacogr/atom-git-control#70] opened 2015-05-07 14:00 UTC
Use ::getRepositories instead
```
Project.getRepo (C:\Users\User\AppData\Local\atom\app-0.196.0\resources\app.asar\src\project.js:579:12)
Object.<anonymous> (C:\Users\User\.atom\packages\git-control\lib\git.coffee:15:17)
Object.<anonymous> (C:\Users\User\.atom\packages\git-control\lib\git.coffee:289:4)
Module._compile (module.js:452:26)
```

**Comment by nounoursheureux** [comment] 2015-05-07 14:27
Duplicate of #64 . This bug has been fixed, just wait for the next release :)

**Comment by MarcelMue** [comment] 2015-05-07 16:37
:+1: 
New release is probably going to come next week, until then this warning will pop up.

**Closed by MarcelMue** 2015-05-07 16:37 UTC
