### ISSUE TITLE
project changed but git repo not change

### ISSUE THREAD

**Issue by ginus** [jacogr/atom-git-control#19] opened 2015-01-19 13:03 UTC
I use project ring manage my projects. 1st I open the Git-Control for my project one, then I changed to project two, now Git-Control throw errors repo destroyed, but it should close repo one and open repo two.

**Comment by MarcelMue** [comment] 2015-05-05 19:45
Duplicate of #26 , but is less informative than the newer duplicate.

**Closed by MarcelMue** 2015-05-05 19:45 UTC
