### ISSUE TITLE
GitRepository.getOriginUrl is deprecated.

### ISSUE THREAD

**Issue by litar1** [jacogr/atom-git-control#67] opened 2015-05-03 17:50 UTC
Use ::getOriginURL instead.
```
GitRepository.getOriginUrl (/usr/share/atom/resources/app.asar/src/git-repository.js:446:7)
Object.hasOrigin (/home/klitarowicz/.atom/packages/git-control/lib/git.coffee:127:16)
GitControlView.fetchMenuClick (/home/klitarowicz/.atom/packages/git-control/lib/git-control-view.coffee:161:24)
GitControlView.update (/home/klitarowicz/.atom/packages/git-control/lib/git-control-view.coffee:68:9)
```

**Comment by MarcelMue** [comment] 2015-05-03 17:51
This seems to be a duplicate of #63 and should be fixed in the next release.

**Closed** 2015-05-03 17:52 UTC
